version: '3.8'
services:
  node:
    image: node:10-slim
    tty: true
    volumes:
      - ./:/srv:rw,delegated
      - ~/.aws/:/root/.aws:ro
    working_dir: /srv
    environment:
      TZ: 'Asia/Tokyo'